### ISSUE TITLE
any plans for varnish 5 ?

### ISSUE THREAD

**Issue by Cactusbone** [zazukoians/docker-varnish#1]
Hello !
Do you plan to add varnish 5 ? maybe as a tag ?

**Comment by ktk** [comment]
@Cactusbone will check it out, does varnish provide it in the debian source?

**Comment by Cactusbone** [comment]
@ktk looks like it can be found at https://packagecloud.io/varnishcache/varnish5

**Comment by Cactusbone** [comment]
Only the link I gave is provided on the official Varnish website, but a
debian package is provided there. 5.0.0 made it for stretch and sid on the
official debian sources, but 5.1.2 did not, and it's the one i'd like for
http/2

**Comment by ktk** [comment]
@Cactusbone I did a first commit with https://github.com/zazukoians/docker-varnish/commit/ef6bd39188fff75edc2248b5b6ded238b3efc0e3 that creates a branch V5. You can try it with:

     git clone -b V5 https://github.com/zazukoians/docker-varnish.git

And then build the docker container according to the readme.

I don't have the time to check if this works and if there are any changes in the configuration right now. Please see if this helps already. If you have stuff I should adjust please let me know.

It's not on Dockerhub, will only push it there once I know it works.

**Comment by Cactusbone** [comment]
Thanks ! I'll try it on tuesday or wednesday, and report back here ☺️

**Comment by Cactusbone** [comment]
Looks like it works :)
I've managed to start it and use my configuration, I'll test it further during the month :)

We were using collectd to monitor our varnish 3/4 installation, not sure how i'll get it to work with a docker instance, I'll report it when i get it to work too

**Comment by ktk** [comment]
@Cactusbone excellent. I have to think about how to maintain two versions, never did that so far. Once I figured that out I will publish it to Dockerhub.

Did you had to adjust anything in the config or is this similar to V4?

**Comment by Cactusbone** [comment]
It's similar to V4 :)

Dockerhub knows how to handle branches so you can simply publish the branch, but it requires you to maintain all the branches.

or use folders like they do for postgres (https://github.com/docker-library/postgres)

**Comment by ktk** [comment]
@Cactusbone tnx will check that out. Is there anything I need to change on the ENV-vars I've set or does that work with V5?

**Comment by Cactusbone** [comment]
@ktk It worked for me.

**Comment by Cactusbone** [comment]
I also needed collectd to monitor varnish so i forked this repo :) Thanks for V5 :)
